### ISSUE TITLE
HTTP 500 when launching the application

### ISSUE THREAD

**Issue by SplunkingArnaud** [georgestarcher/TA-SyncKVStore#1]
Hello,

I am getting an HTTP 500 when trying to launch the app (TA-SyncKVStore-master/inputs): 
**An error occurred while reading the page template. See web_service.log for more details**

I could not find any clue on web_service.log.
I am running Splunk 7.0.

Regards.

**Comment by georgestarcher** [comment]
I installed it and went to configuration fine on a 7.0.1 install of splunk on the app from Splunk base. You should not be installing the app as "master" from this git repo. You are breaking the app name/path in splunk. Closing issue.
