### ISSUE TITLE
Modular alert doesn't copy all rows of large table

### ISSUE THREAD

**Issue by sodle** [georgestarcher/TA-SyncKVStore#3]
I have a very large KVStore table that I'm trying to copy over - nearly 2 million rows. Using the modular alert version of SyncKVStore, only the first 300k or so rows seem to be copied. Not seeing any errors in _internal, the lookup on the target server is just significantly smaller than on the source.

**Comment by georgestarcher** [comment]
Alert actions work on search results. I doubt inputlookup or even normal search results are going to pass that many rows. You should investigate splunk limits there first.

**Comment by georgestarcher** [comment]
Looks more like its a time limit issue. Where splunk only allows it to run for a time period and kill it. 2 million rows is likely to take a really long time. You can contact support at splunk or research how long it lets alert actions run.

**Comment by sodle** [comment]
OK, thanks. I'll look further into it. As for your doubts, yeah we actually do have that many rows. This is a lookup of ID number to name for everyone in our organization.

**Comment by georgestarcher** [comment]
Update this file. Found the timeout. I has looked in limits.conf not alert_actions.conf
https://github.com/georgestarcher/TA-SyncKVStore/blob/master/default/alert_actions.conf

**Comment by sodle** [comment]
Yep, that was the problem - turns out copying 2m rows takes about half an hour. Upping the time limit to 1h as shown in that file allows the full table to be copied. Thanks, George!
