### ISSUE TITLE
Modular Input ERRORs on Spunk Enterprise 8.1.2 Windows

### ISSUE THREAD

**Issue by dimarra** [georgestarcher/TA-SyncKVStore#8]
Download and install of this TA produces the following messages on splunkd.log on restart.

03-17-2021 20:55:59.885 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_index:  Traceback (most recent call last):
03-17-2021 20:55:59.885 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_index:    File "F:\Splunk\etc\apps\TA-SyncKVStore\bin\kvstore_to_index.py", line 8, in <module>
03-17-2021 20:55:59.885 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_index:      import modinput_wrapper.base_modinput
03-17-2021 20:55:59.885 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_index:    File "F:\Splunk\etc\apps\TA-SyncKVStore\bin\ta_synckvstore\modinput_wrapper\base_modinput.py", line 10, in <module>
03-17-2021 20:55:59.885 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_index:      from solnlib.packages.splunklib import modularinput as smi
03-17-2021 20:55:59.885 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_index:    File "F:\Splunk\etc\apps\TA-SyncKVStore\bin\ta_synckvstore\solnlib\__init__.py", line 19, in <module>
03-17-2021 20:55:59.885 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_index:      from . import (
03-17-2021 20:55:59.885 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_index:    File "F:\Splunk\etc\apps\TA-SyncKVStore\bin\ta_synckvstore\solnlib\acl.py", line 21, in <module>
03-17-2021 20:55:59.885 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_index:      from . import splunk_rest_client as rest_client
03-17-2021 20:55:59.885 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_index:    File "F:\Splunk\etc\apps\TA-SyncKVStore\bin\ta_synckvstore\solnlib\splunk_rest_client.py", line 24, in <module>
03-17-2021 20:55:59.885 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_index:      import urllib2
03-17-2021 20:55:59.885 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_index:  ModuleNotFoundError: No module named 'urllib2'
03-17-2021 20:55:59.901 +1100 ERROR ModularInputs - Introspecting scheme=kvstore_to_index: script running failed (exited with code 1).
03-17-2021 20:55:59.901 +1100 ERROR ModularInputs - Unable to initialize modular input "kvstore_to_index" defined in the app "TA-SyncKVStore": Introspecting scheme=kvstore_to_index: script running failed (exited with code 1)..
03-17-2021 20:56:00.120 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_kvstore:  Traceback (most recent call last):
03-17-2021 20:56:00.120 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_kvstore:    File "F:\Splunk\etc\apps\TA-SyncKVStore\bin\kvstore_to_kvstore.py", line 8, in <module>
03-17-2021 20:56:00.120 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_kvstore:      import modinput_wrapper.base_modinput
03-17-2021 20:56:00.120 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_kvstore:    File "F:\Splunk\etc\apps\TA-SyncKVStore\bin\ta_synckvstore\modinput_wrapper\base_modinput.py", line 10, in <module>
03-17-2021 20:56:00.120 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_kvstore:      from solnlib.packages.splunklib import modularinput as smi
03-17-2021 20:56:00.120 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_kvstore:    File "F:\Splunk\etc\apps\TA-SyncKVStore\bin\ta_synckvstore\solnlib\__init__.py", line 19, in <module>
03-17-2021 20:56:00.120 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_kvstore:      from . import (
03-17-2021 20:56:00.120 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_kvstore:    File "F:\Splunk\etc\apps\TA-SyncKVStore\bin\ta_synckvstore\solnlib\acl.py", line 21, in <module>
03-17-2021 20:56:00.120 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_kvstore:      from . import splunk_rest_client as rest_client
03-17-2021 20:56:00.120 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_kvstore:    File "F:\Splunk\etc\apps\TA-SyncKVStore\bin\ta_synckvstore\solnlib\splunk_rest_client.py", line 24, in <module>
03-17-2021 20:56:00.120 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_kvstore:      import urllib2
03-17-2021 20:56:00.120 +1100 ERROR ModularInputs - <stderr> Introspecting scheme=kvstore_to_kvstore:  ModuleNotFoundError: No module named 'urllib2'
03-17-2021 20:56:00.135 +1100 ERROR ModularInputs - Introspecting scheme=kvstore_to_kvstore: script running failed (exited with code 1).
03-17-2021 20:56:00.135 +1100 ERROR ModularInputs - Unable to initialize modular input "kvstore_to_kvstore" defined in the app "TA-SyncKVStore": Introspecting scheme=kvstore_to_kvstore: script running failed (exited with code 1)..

These message are on Splunk Enterprise 8.1.2.

Thanks

**Comment by georgestarcher** [comment]
This is old and unsupported. It will not be updated for recent versions of Splunk. Sorry
